### ISSUE TITLE
Versioning is not following SemVer

### ISSUE THREAD

**Issue by okainov** [asottile/flake8-2020#105]
Not sure whether this can be properly fixed now, but at least I'm going post is as feedback item.

I do expect libraries to follow at least some kind of semver-alike versioning. If there are breaking changes, I do expect `major` version to be bumped. However it's not the case with `flake8-2020`, we got an error when trying to update `1.6.1 -> 1.7.0`:

> flake8-2020 1.7.0 depends on flake8>=5

We do use flake8 less than 5, because there are other plugins (namely, `wemake-python-styleguide`) which require older `flake8`. And changing to the newer `flake8` is a major version bump. This was really unexpected when `flake8-2020` got a *major* change *breaking backward compatibility* without bumping its major version.

Could you please check and maybe at least somehow improve the release process to avoid such issues in the future? Ideally would be to fix current releases, but I understand this is unlikely to happen....

**Comment by hugovk** [comment]
The public API of flake8-2020 didn't change, so I don't think a major bump here is needed.

See:

* ["What should I do if I update my own dependencies without changing the public API?"](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)
* ["Do I need to increment my package’s version when I require a new major version of one its dependencies? No."](https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes/)


And the next version of wemake-python-styleguide should support Flake8 5:

* https://github.com/wemake-services/wemake-python-styleguide/pull/2518
* https://github.com/wemake-services/wemake-python-styleguide/issues/2514

**Comment by okainov** [comment]
>The public API of flake8-2020 didn't change, so I don't think a major bump here is needed.

TBH for me as a user I think major bumps are not necessarily "public API" changes in the context you mean, but also any general "backward incompatible changes". For example, dropping old Python versions support, or switching major versions of dependencies - both of those changes would be breaking for me as a user... Because new version of the tool does not work any more with the environment where it used to work before...

**Comment by hugovk** [comment]
They also say you don't need to bump the major for dropping old Python versions:

"Do I need to increment my package’s major version when I update the language requirement? No."

Thanks to `python_requires`, pip will still install the last supported version for old Python versions: "Nothing’s broken, you just won’t be receiving any new updates."

**Comment by asottile** [comment]
@okainov you're wrong and free to use the old version if it inconveniences you -- but a dependency version change is not a semantic break and whining here about it is not a good use of anyone's time
