### ISSUE TITLE
Small optimisation of YTT202

### ISSUE THREAD

**Issue by hugovk** [asottile/flake8-2020#2]
With this code:

```python
import six
if not six.PY3:
    pass
```

The plugin correctly gives:

```console
$ flake8 --select YTT 1.py
1.py:2:8: YTT202: `six.PY3` referenced (python4), use `not six.PY2`
```

Perhaps it could detect the `not` before `six.PY3`, and suggest a clean `six.PY2` instead?

For example:

```console
$ flake8 --select YTT 1.py
1.py:2:X: YTT20X: `not six.PY3` referenced (python4), use `six.PY2`
```

That is:

```python
# Bad
if not six.PY3:

# Better (sort of)
if not not six.PY2:

# Best
if six.PY2:
```

**Comment by asottile** [comment]
yeah it would be better, but it'd be very hard to implement -- and since this isn't a code formatter I'm inclined to let the human do the right thing 🤷‍♂
