### ISSUE TITLE
Treat `PY3` just as `six.PY3`

### ISSUE THREAD

**Issue by pquentin** [asottile/flake8-2020#23]
@hugovk submitted a pull request to urllib3 based on this plugin: https://github.com/urllib3/urllib3/pull/1669. Thanks! But it failed to catch all issues, as `PY3` was sometimes imported directly. See https://github.com/urllib3/urllib3/pull/2004 for examples.

This may cause false positives, though.

**Comment by asottile** [comment]
`PY3` could be defined correctly as `sys.version_info >= (3,)` so this isn't really valid -- it does correctly identify `six.PY3` and `from six import PY3` already

**Comment by pquentin** [comment]
I see, that makes sense!

For what it's worth, the `from six import PY3` detection does not work in the case of urllib3 since we vendor six, but there's not much you can do about it.

**Comment by asottile** [comment]
correct, we'd need to do dynamic analysis which at best would be slow and at worst would be solving the halting problem
